# Generated by Django 6.0.5 on 2026-05-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('aguardando_liberacao', 'Aguardando Liberação'), ('em_cotacao', 'Em Cotação'), ('cotacao_encerrada', 'Cotação Encerrada'), ('aguardando_aprovacao_final', 'Aguardando Aprovação Final'), ('pedido_tr', 'Pedido / TR'), ('aguardando_nota', 'Aguardando Nota Fiscal'), ('nota_lancada', 'Nota Lançada'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pagamento_liberado', 'Pagamento Liberado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='solicitada', max_length=50)),
                ('prioridade', models.CharField(choices=[('Normal', 'Normal'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Normal', max_length=20)),
                ('solicitante', models.CharField(blank=True, max_length=150)),
                ('fornecedor', models.CharField(blank=True, max_length=150)),
                ('dias_parado', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
