# Generated by Django 6.0.5 on 2026-05-09 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=255)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='compras.compra')),
            ],
        ),
    ]
