# Generated by Django 6.0.5 on 2026-05-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_historicocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='departamento',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_solicitacao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='compra',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('aguardando_liberacao', 'Aguardando Liberação'), ('em_cotacao', 'Em Cotação'), ('cotacao_encerrada', 'Cotação Encerrada'), ('aguardando_aprovacao_final', 'Aguardando Aprovação Final'), ('pedido_tr', 'Pedido / TR'), ('adiantamento_fornecedor', 'Adiantamento ao Fornecedor'), ('aguardando_nota', 'Aguardando Nota Fiscal'), ('nota_lancada', 'Nota Lançada'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pagamento_liberado', 'Pagamento Liberado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='solicitada', max_length=50),
        ),
    ]
